### PR TITLE
Premium fix Billing API loading time + add checks before buying Premium

### LINKED ISSUE #1198: Include obfuscated id flow as a isBillingAvailable() parameter
See title

### PR DESCRIPTION
**Pull request by Kokobe**
The timing and use of fetching the `ProductDetails` and `ExistingPurchases` of a user from the Google Billing API was wrong. This made the Plans screen take a while to load its Subscription Offering data. 

This PR: 
* Reduces the loading time for fetching subscription offering data. 
* "Learn more about Premium" button in `ProfileSettingsPane` now leads the user to the neeva.com/settings/membership website in a browser tab if the Billing API or Premium is unavailable for them to purchase on this device. 
* Added flows and verbal logs for when Google Billing API and Neeva Premium Purchase ready.
* Adds a `ATTEMPTS_TO_ASSUME_FAILURE` to `BillingClientController` so that the user doesn't have to wait for the `MAX_ATTEMPTS` to finish. 
* Introduces a 1 minute timeout in case the user's internet connection is too slow and we can't fetch Billing information. 
* Adds a Loading indicator and disables the "Let's go" button until we get enough information to determine if the user can purchase Premium or not.
* Cleans up code in ActivityStarter

### Pointers to help with review
* https://www.figma.com/file/dylvDPB69JG9U1rzZ3HQ52/Android-Premium?node-id=0%3A1
* 1 min timeout for Welcome Screen conversation: https://neevaco.slack.com/archives/C03PQUPJJDP/p1674001779236809

### How was this tested?
- [x] I tested this manually on `debug`
- [x] I tested this manually on `staging` or `release`
- [ ] I added automated tests
- [ ] Existing automated tests cover some of my changes
- [ ] Existing automated tests cover all of my changes
- [x] I checked that `@Previews` still work in Android Studio

# Manual test cases

## ProfilePane Changes
ProfilePane + press "Learn more about Premium" + billing and premium available -> Sends user to Plans screen.

https://user-images.githubusercontent.com/20916043/213127187-621d9681-a119-4aad-a5cf-f63aba7b2c01.mp4

ProfilePane + press "Learn more about Premium" + billing and premium not available -> Sends user to neeva.com/settings/membership

https://user-images.githubusercontent.com/20916043/212504449-348072a2-dd32-4069-b133-3e364ef64e93.mp4

## Welcome Screen Lets Go button disabling

FirstRun Billing disabled -- no effect on Sign-in because the toggle will cause the `isBillingAvailableFlow` to immediately return false:

https://user-images.githubusercontent.com/20916043/212504469-14fc6af3-ab47-4134-b08e-2dea20827aa6.mp4

FirstRun Billing enabled -> let's go button is disabled until Billing API ready

https://user-images.githubusercontent.com/20916043/213129511-8a58748c-6133-4cdc-9179-a302a0c0e951.mp4

FirstRun but Billing never gets back to us (1 min of waiting time before we allow the user to move on)

https://user-images.githubusercontent.com/20916043/213098592-1513c827-fce8-4d4e-b558-27727be2bc65.mov

### CODE REVIEW

File: app/src/test/java/com/neeva/app/userdata/NeevaUserTest.kt [hunk 1]
```diff
@@ -93,7 +93,7 @@ class NeevaUserTest : BaseTest() {
             sharedPreferencesModel = sharedPreferencesModel,
             loginToken = loginToken,
             networkHandler = networkHandler,
-            billingClientController = billingClientController
+            billingClientController = billingClientController,
```
Comment (dan-alcantara-neeva) [inline app/src/test/java/com/neeva/app/userdata/NeevaUserTest.kt:96]: Unnecessary comma changes; revert all of these to make the PR cleaner

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt [hunk 2]
```diff
@@ -124,12 +127,17 @@ internal fun ConsentCheckbox(
 
 @Composable
 private fun ContinueButtons(
-    onContinueInWelcomeScreen: () -> Unit,
+    onContinueInWelcomeScreen: (() -> Unit)?,
     navigateToSignIn: () -> Unit,
 ) {
+    var onLetsGo = { }
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt:133]: Can you just use a regular if statement here instead of this funky `?.let` block?

File: app/src/main/java/com/neeva/app/settings/SettingsController.kt [hunk 3]
```diff
@@ -195,13 +199,22 @@ class SettingsControllerImpl(
...
-                appNavModel.showWelcomeFlow(
-                    LoginReturnParams(
-                        activityToReturnTo = NeevaActivity::class.java.name,
-                        screenToReturnTo = AppNavDestination.SETTINGS.name
-                    ),
-                    purpose = WelcomeFlowActivity.Companion.Purpose.BROWSE_PLANS
-                )
+                val canPurchasePremium = subscriptionManager.isBillingAvailableFlow.value == true &&
+                    subscriptionManager.isPremiumPurchaseAvailableFlow.value == true
+                when (canPurchasePremium) {
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/settings/SettingsController.kt:204]: This is just an if statement.

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt [hunk 4]
```diff
@@ -177,7 +178,7 @@ class WelcomeFlowActivity : AppCompatActivity() {
                     ) {
                         composable(Destinations.WELCOME.name) {
                             WelcomeScreen(
-                                onContinueInWelcomeScreen = ::onContinueInWelcomeScreen,
+                                onContinueInWelcomeScreen = onContinueInWelcomeScreen(),
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt:181]: This function name and invocation are misleading: you're calling a function to create another function that is actually called when the user hits the button.  Instead of doing that, can you just call the function like you used to and make that do the correct checks?

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt [hunk 5]
```diff
@@ -474,16 +469,27 @@ class WelcomeFlowActivity : AppCompatActivity() {
...
-            isPremiumPurchaseAvailable() -> {
-                welcomeFlowNavModel.showPlans()
-            }
-            !setDefaultAndroidBrowserManager.isNeevaTheDefaultBrowser() -> {
-                welcomeFlowNavModel.showSetDefaultBrowser()
-            }
-            else -> {
-                finishWelcomeFlow()
+    @Composable
+    private fun onContinueInWelcomeScreen(): (() -> Unit)? {
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt:473]: Why is this a Composable?

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 6]
```diff
@@ -39,40 +45,78 @@ class SubscriptionManager(
...
         get() = SharedPrefFolder.FirstRun.SelectedSubscriptionTag.getFlow(sharedPreferencesModel)
 
-    val productDetailsFlow = billingClientController.productDetailsFlow
-    val purchasesFlow = billingClientController.purchasesFlow
-    val obfuscatedUserIDFlow = billingClientController.obfuscatedUserIDFlow
+    val productDetailsWrapperFlow = billingClientController.productDetailsFlowWrapper
+    val existingPurchasesFlow = billingClientController.purchasesFlow
+    val isBillingAvailableFlow = productDetailsWrapperFlow
+        .combine(existingPurchasesFlow) { productDetailsWrapper, existingPurchases ->
+            if (!settingsDataModel.getSettingsToggleValue(SettingsToggle.DEBUG_ENABLE_BILLING))
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:60]: Always put braces when it ends up on multiple lines

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 7]
```diff
@@ -39,40 +45,78 @@ class SubscriptionManager(
...
+                return@combine false
 
-    val hasAnnualPremiumPlan: Flow<Boolean> = billingClientController.purchasesFlow
-        .map { purchaseList ->
-            purchaseList.any { purchase ->
-                purchase.products.contains(BillingSubscriptionPlanTags.ANNUAL_PREMIUM_PLAN)
+            // If the Billing information has not been fetched yet, then we still don't know if
+            // Billing is available for this user.
+            if (!productDetailsWrapper.isSet || existingPurchases == null) {
+                Log.v(
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:66]: Timber, not Log.

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt (hunk 5 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt:473]: I wanted to make the WelcomeScreenComposable re-compose itself whenever the `isBillingAvailableFlow` changed see: `val isBillingAvailable = subscriptionManager.isBillingAvailableFlow.collectAsState().value`

I can pull that out though and make this function not a Composable

File: app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt [hunk 8]
```diff
@@ -53,9 +54,12 @@ class FetchPurchasesManager(
                     _purchasesFlow.value = purchaseList
                 } else {
                     fetchContinuation.resume(false)
+                    if (shouldAssumeFailureForNow) {
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt:57]: What is `shouldAssumeFailureForNow` supposed to mean?  Add it to the kdoc.

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt (hunk 5 above)
Comment (dan-alcantara-neeva) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt:473]: It's a fragile link, regardless.  If you want to force something somewhere else to recompose when necessary, make the Composable have the logic for knowing when to trigger it -- not a callback that a button on that screen displays.

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt (hunk 7 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:66]: But Timber doesn't work on release builds? I guess I can look into it and add it to the growing scope of Premium

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt (hunk 2 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt:133]: Good point lol

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 9]
```diff
@@ -146,6 +190,16 @@ class SubscriptionManager(
             }
     }
 
+    private fun collectIsPremiumPurchaseAvailable(onResult: (Boolean) -> Unit) {
+        coroutineScope.launch(dispatchers.io) {
+            isPremiumPurchaseAvailableFlow.collect {
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:195]: Do you need this to stay alive after the first `it != null` condition is hit?  Can you make the job terminate itself so that it's not just constantly running?  There should be operators other than `collect` that would help you do that...

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 10]
```diff
@@ -168,26 +222,41 @@ class SubscriptionManager(
...
-        val offerToken = leastPricedOfferToken(offerDetails)
-        val obfuscatedUserID = billingClientController.obfuscatedUserIDFlow.value
-
-        if (isPremiumPurchaseAvailable()) {
-            offerToken?.let {
-                val billingParams = billingFlowParamsBuilder(
-                    productDetails = productDetails,
-                    offerToken = it,
-                    obfuscatedUserID = obfuscatedUserID
+        coroutineScope.launch(dispatchers.io) {
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:225]: You've introduced a Job that will run whenever `buy` is called.  Can you guarantee that `buy()` will only called once?  If not, you will end up with two Jobs running in parallel.

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 11]
```diff
@@ -238,5 +307,6 @@ class SubscriptionManager(
 
     companion object {
         val QUEUE_BUY_ON_SIGN_IN_JOB_NAME = "WelcomeFlow: QueueBuyOnSuccessfulSignIn"
+        val TAG = "SubscriptionManager"
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:310]: No more tags; we're using Timber.

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt (hunk 2 above)
Comment (dan-alcantara-neeva) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt:133]: Behavior is more of a UX question.  If the user is offline when they start the app, will this button ever be enabled?

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt (hunk 4 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeFlowActivity.kt:181]: I need to pass in a `isBillingAvailable` here because `onContinueInWelcomeScreen` depends on that variable. I'll rename the function to: `getOnContinueInWelcomeScreen()`

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt (hunk 6 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:60]: This if statement is only 1 line, but I'll put braces around it anyways and add a log here

Comment (dan-alcantara-neeva) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:60]: If the return ends up on the next line, you have to add braces.

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt (hunk 9 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:195]: Is calling `this@launch.cancel()` after `onResult(it)` happens an adequate way to do this? 

It will cancel the job created by `launch`, which will end the collecting when the `it != null` condition is hit

Comment (dan-alcantara-neeva) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:195]: Is there a `single` or something similar?  Might need to combine it with a filter

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt (hunk 2 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt:133]: Yes this button will be enabled in 1.3 seconds because of my `ATTEMPTS_TO_ASSUME_FAILURE` in `BillingClientController`.

Basically, if we the fetch ProductDetails job fails twice, we tell the the UI to assume the job failed and allow the user to move on to the next screen (not PLANS related). This doesn't mean we stop trying to fetch it (it's still happening with exponential backoff), but we allow the user to continue on. 

You can see this in my "FirstRun billing disabled" video in the PR description

Comment (dan-alcantara-neeva) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt:133]: Are you just making the button do nothing by removing the onClick?  Can you properly mark the button as disabled so that it doesn't stay blue and look clickable?

File: app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt (hunk 8 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt:57]: I've added documentation in `BillingClientController`'s `ATTEMPTS_TO_ASSUME_FAILURE` constant which is where the variable originates and is ultimately passed onto `FetchProductDetailsManager` and `FetchPurchasesManager`

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt (hunk 9 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:195]: From what I'm reading it seems that `single` is still a `collect` that is constantly running. Why is single better? 

Screen Shot 2023-01-17 at 2 48 57 PM

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt (hunk 7 above)
Comment (dan-alcantara-neeva) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:66]: We shouldn't be mixing and matching Timber and Log usage; we should be sticking with a single framework for logging our messages.  If Timber isn't good enough for what we need, we should rip it back out.

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt (hunk 11 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:325]: Timber is still not working on release

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 12]
```diff
@@ -36,43 +43,92 @@ class SubscriptionManager(
...
+    val productDetailsWrapperFlow = billingClientController.productDetailsFlowWrapper
+    val existingPurchasesFlow = billingClientController.purchasesFlow
+    val isBillingAvailableFlow = productDetailsWrapperFlow
+        .combine(existingPurchasesFlow) { productDetailsWrapper, existingPurchases ->
+            if (!settingsDataModel.getSettingsToggleValue(SettingsToggle.DEBUG_ENABLE_BILLING)) {
+                Log.v(
+                    TAG,
+                    "Billing not available because the dev `Enable billing` settings toggle " +
+                            "is disabled."
+                    )
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:71]: ktlint moved this parenthesis here?

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt (hunk 7 above)
Comment (dan-alcantara-neeva) [reply app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:78]: Talked offline; it's fine to use Log for now because Timber isn't doing what we need in release builds.  Will revisit once the rest of the flow is in place.

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 13]
```diff
@@ -141,11 +197,23 @@ class SubscriptionManager(
...
             }
     }
 
+    private fun collectIsPremiumPurchaseAvailable(onResult: (Boolean) -> Unit) {
+        buySubscriptionCoroutineScope.launch(dispatchers.io) {
+            isPremiumPurchaseAvailableFlow
+                .collect {
+                    Log.e("KOBE", "Collected Premium Purchase available")
+                    if (it == true) {
+                        onResult(true)
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:211]: Still need this Job to be canceled so that it doesn't keep firing your callback

File: app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt (hunk 2 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/welcomeflow/WelcomeScreen.kt]: Lol! No but it wasn't clear since that logic was happening a level lower... I can move it up

**Comment by Kokobe** [comment]
Updated the videos @dan-alcantara-neeva

File: app/src/main/res/values/strings.xml [hunk 14]
```diff
@@ -1029,6 +1029,9 @@
     <!-- [WelcomeFlow] Text for Settings Row to learn more about the Premium subscription. -->
     <string name="welcomeflow_learn_more_about_premium">Learn more about Premium</string>
 
+    <!-- [WelcomeFlow] In the Welcome Screen, this text tells the user that we are loading and we are not ready to show them the next Screen yet. Replaces the "Let's go" Button's text label while we are loading. -->
+    <string name="welcomeflow_loading">Loading</string>
```
Comment (dan-alcantara-neeva) [inline app/src/main/res/values/strings.xml:1033]: Just make this a generic string called "loading" so that we can reuse it.

File: app/src/main/java/com/neeva/app/appnav/ActivityStarter.kt [hunk 15]
```diff
@@ -17,6 +18,18 @@ import timber.log.Timber
 
 class ActivityStarter(private val appContext: Context, private val popupModel: PopupModel) {
 
+    fun safeStartActivityWithoutActivityTransition(intent: Intent) {
+        safeStartActivityForIntent(
+            intent = intent,
+            // Nullify the transition animation to hide the fact that we're switching Activities.
+            options = ActivityOptionsCompat.makeCustomAnimation(
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/appnav/ActivityStarter.kt:25]: Just put this on one line; we can't even name what each argument is because it's a Java call.

File: app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt [hunk 16]
```diff
@@ -223,12 +221,11 @@ class SubscriptionManager(
         tag: String?,
         onBillingFlowFinished: (BillingResult) -> Unit
     ) {
-        buySubscriptionCoroutineScope.cancel()
-        buySubscriptionCoroutineScope = CoroutineScope(Job() + dispatchers.main)
+        cancelPurchaseJobsAndResetScope()
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/SubscriptionManager.kt:224]: Are you down to one `Job` being launched and the `coroutineScope` being used in one place?  Can you just hold onto a `Job?` instead of creating another CoroutineScope?  You can call `cancel()` on it when you're done and create a new one when needed.

File: app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt [hunk 17]
```diff
@@ -194,4 +188,17 @@ class BillingClientController(
...
+    companion object {
+        // region Retrying BillingClient connection parameters
+        internal val SLOW_CONNECTION_WAIT_TIME = 1000L * 60
+        internal val MAX_ATTEMPTS = 5
+        private val FIRST_RETRY_WAIT_TIME = 300L
+        private val RETRY_WAIT_TIME_MULTIPLIER = 2.0
+        // If a job fails this many times, we will assume failure for now. We will continue to try the
+        // job in the background until the max attempts have been finished.
+        private val ATTEMPTS_TO_ASSUME_FAILURE = 4
+        private var attempts = 0
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt:201]: Why is this on the companion object?

File: app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt [hunk 18]
```diff
@@ -32,6 +35,15 @@ class FetchPurchasesManager(
 
     private var callback: (BillingResult) -> Unit = { }
 
+    private val slowInternetConnectionTimer: Job
+
+    init {
+        slowInternetConnectionTimer = coroutineScope.launch(dispatchers.io) {
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/billingclient/FetchPurchasesManager.kt:41]: This should be launched at the same time as the `fetchPurchases` call because you're timing that -- not when this class was first initialized.

File: app/src/main/java/com/neeva/app/welcomeflow/SharedComposables.kt [hunk 19]
```diff
@@ -32,26 +34,40 @@ internal fun WelcomeFlowButton(
...
-            modifier = Modifier.padding(vertical = Dimensions.PADDING_SMALL)
-        ) {
-            Text(
-                text = primaryText,
-                style = MaterialTheme.typography.titleMedium
-            )
-            if (secondaryText != null) {
+        Row(verticalAlignment = Alignment.CenterVertically) {
+            if (!enabled) {
+                CircularProgressIndicator(
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/welcomeflow/SharedComposables.kt:47]: 1. It's a small thing, but Hwi wanted this to show up only after 300 milliseconds.
2. Also a small thing, but you could use a `Crossfade` composable that's dependent on the `enabled` flag as its `targetState` so that you could show the button fading as it goes from being disabled to enabled.

**Review by dan-alcantara-neeva — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt (hunk 17 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/billingclient/BillingClientController.kt:201]: moved it into the class, you're right only constants should be in here

File: app/src/main/java/com/neeva/app/welcomeflow/SharedComposables.kt (hunk 19 above)
Comment (Kokobe) [reply app/src/main/java/com/neeva/app/welcomeflow/SharedComposables.kt:47]: Added this to a list of Polish action items, will punt on this issue for the next PR

**Review by dan-alcantara-neeva — APPROVED** [review]

File: app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt [hunk 20]
```diff
@@ -28,8 +43,18 @@ class FetchProductDetailsManager(private val billingClientController: BillingCli
                     .build()
             )
         )
+    private val slowInternetConnectionTimer: Job
 
-    suspend fun fetchProductDetails(): Boolean = suspendCoroutine { fetchContinuation ->
+    init {
+        slowInternetConnectionTimer = coroutineScope.launch(dispatchers.io) {
```
Comment (dan-alcantara-neeva) [inline app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt:49]: I think I asked you to move this offline; we want this to start when the job does and not when the class is initialized.

Comment (Kokobe) [reply app/src/main/java/com/neeva/app/billing/billingclient/FetchProductDetailsManager.kt:49]: Fixed this in #1235
